version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1-node
    environment:
      - NOKOGIRI_USE_SYSTEM_LIBRARIES: true
      - CC_TEST_REPORTER_ID: 73fdd74c0ec197833fe8f82b754812756a607cd40323fd5c59fdefbd142c7eba
    branches:
      only:
        - master
        - /feature-.*/
    steps:
      - checkout
      
# --- Install Tools ---

      - run:
          name: install node goodies
          command: |
            # sudo npm install
            npm install

#      - run:
#          name: install ruby/gem goodies
#          command: |
#            # sudo npm run init-gems
#            npm run init-gems

# --- Run Build Steps ---

      # css reset? sass/less? [https://github.com/necolas/normalize.css]
      # prettifier? uglifier?

      - run:
          name: run unit tests
          command: |
            npm run test

#      - run:
#          name: install coverage depencencies
#          command: |
#            sudo composer self-update
#            composer install -n --prefer-dist

      - run:
          name: install code climate test-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter

      - run:
          name: run coverage tests
          command: |
            ./cc-test-reporter before-build
            npm run coverage
            ./cc-test-reporter format-coverage -t lcov $CIRCLE_ARTIFACTS/coverage/.resultset.json
            ./cc-test-reporter upload-coverage
#            ./cc-test-reporter after-build --exit-code $EXIT_CODE
